services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IngHubsCreditModule
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      PORT: 8080
    networks:
      - ing-hubs
networks:
  ing-hubs: