services:
  mysql:
    image: mysql:8.0.1
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: spring
      # MYSQL_USER: root (root user is created by default)
      MYSQL_USER: anil
      MYSQL_PASSWORD: senocak
      MYSQL_ROOT_PASSWORD: senocak
    ports:
      - 3310:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  backend:
    build:
      context: ./spring
      dockerfile: Dockerfile
    container_name: spring
    ports:
      - 8080:8080
    restart: always
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DB: turkcell
      MYSQL_USER: root
      MYSQL_PASSWORD: senocak
    depends_on:
      - mysql
    networks:
      - backend
volumes:
  mysql-data:
networks:
  backend: