server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3310}/${MYSQL_DB:turkcell}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:senocak}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:changelog.xml
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: '#{1 * 60 * 60 * 1000}' # 5 minutes in milliseconds
springdoc:
  api-docs:
    path: /api/v1/swagger
  version: @project.version@